server:
  port: 9195

spring:
  application:
    name: novel-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

shenyu:
  register:
    registerType: nacos
    serverLists: 127.0.0.1:8848
    props:
      username: nacos
      password: nacos
  discovery:
    selector:
      type: nacos
      serverList: 127.0.0.1:8848
      namespace: public
  httpclient:
    strategy: webClient

management:
  endpoints:
    web:
      exposure:
        include: '*'
