spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
        register-enabled: true
        fail-fast: false
      config:
        server-addr: localhost:8848
        file-extension: yml
  datasource:
    url: jdbc:mysql://localhost:3306/novel_payment?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
