server:
  port: 8084

spring:
  application:
    name: novel-payment-service
  config:
    import:
      - optional:nacos:novel-payment-service.yml?refresh=true
      - optional:nacos:application-common.yml?group=DEFAULT_GROUP&refresh=true
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto

sa-token:
  token-name: Authorization

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-}]"
  level:
    com.novel.cloud.payment.infrastructure.mapper: DEBUG
