server:
  port: 8084

spring:
  application:
    name: novel-payment-service
  config:
    import:
      - optional:nacos:novel-payment-service.yml?refresh=true
      - optional:nacos:application-common.yml?group=DEFAULT_GROUP&refresh=true
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: '*'
