server:
  port: 8084

spring:
  application:
    name: novel-activity
  datasource:
    url: jdbc:mysql://localhost:3306/novel_activity?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

sa-token:
  token-name: Authorization
  timeout: -1
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true
