server:
  port: 8081

spring:
  application:
    name: novel-user-service
  config:
    import:
      - optional:nacos:novel-user-service.yml?refresh=true
      - optional:nacos:application-common.yml?group=DEFAULT_GROUP&refresh=true
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

sa-token:
  timeout: -1
  activity-timeout: -1
  is-auto-renew: false
  is-concurrent: true
  is-share: true
  token-style: random-128
  is-log: true
  jwt-secret-key: novel-user-secret-key-change-me

management:
  endpoints:
    web:
      exposure:
        include: '*'
