server:
  port: 8082

spring:
  application:
    name: novel-book-service
  config:
    import:
      - optional:nacos:novel-book-service.yml?refresh=true
      - optional:nacos:application-common.yml?group=DEFAULT_GROUP&refresh=true
  profiles:
    active: dev

sa-token:
  token-name: Authorization #所有实例配置必须完全一致
  timeout: 86400

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    level: "%5p %X{traceId}"
  level:
    com.novel.cloud.book.infrastructure.mapper: DEBUG
