server:
  port: 8082

spring:
  application:
    name: novel-book-service
  config:
    import:
      - optional:nacos:novel-book-service.yml?refresh=true
      - optional:nacos:application-common.yml?group=DEFAULT_GROUP&refresh=true
  profiles:
    active: dev
sa-token:
  token-name: Authorization #所有实例配置必须完全一致
  timeout: 86400

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


management:
  endpoints:
    web:
      exposure:
        include: '*'
