server:
  port: 8081

spring:
  application:
    name: novel-user-server
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/novel_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

shenyu:
  client:
    register-type: http
    server-lists: http://127.0.0.1:9195
    props:
      contextPath: /user
      appName: novel-user-server

management:
  endpoints:
    web:
      exposure:
        include: '*'
